version: '3'

services:
  alpine-test:
    build:
      context: .
      dockerfile: Dockerfile.alpine
    container_name: alpine-test
    stdin_open: true
    tty: true
    volumes:
      - ./alpine:/app

  debian-test:
    build:
      context: .
      dockerfile: Dockerfile.debian
    container_name: debian-test
    stdin_open: true
    tty: true
    volumes:
      - ./debian:/app
